In [1]:
import selenium
from selenium import webdriver
import pandas as pd
from selenium.webdriver.common.by import By
import warnings
warnings.filterwarnings('ignore')
import time

In [2]:
driver = webdriver.Chrome(r'C:\Users\prasad kalekar\Selenium\chromedriver.exe')
driver.maximize_window()
driver = webdriver.Chrome('chromedriver.exe')
url = ' https://www.forbes.com/?sh=605023e82254'

driver.get(url)

In [4]:
name = []
b = driver.find_elements(By.XPATH,'//div[@class="personName"]')
for i in b:
    name.append(i.text)
name

['Elon Musk',
 'Jeff Bezos',
 'Bernard Arnault & family',
 'Bill Gates',
 'Warren Buffett',
 'Larry Page',
 'Sergey Brin',
 'Larry Ellison',
 'Steve Ballmer',
 'Mukesh Ambani',
 'Gautam Adani',
 'Michael Bloomberg',
 'Carlos Slim Helu & family',
 'Francoise Bettencourt Meyers & family',
 'Mark Zuckerberg',
 'Jim Walton',
 'Zhong Shanshan',
 'Alice Walton',
 'Rob Walton',
 'Changpeng Zhao',
 'Charles Koch',
 'Julia Koch & family',
 'Amancio Ortega',
 'Michael Dell',
 'Zhang Yiming',
 'David Thomson & family',
 'Phil Knight & family',
 'Dieter Schwarz',
 'Robin Zeng',
 'MacKenzie Scott',
 'Rodolphe Saadé & family',
 'François Pinault & family',
 'Klaus-Michael Kuehne',
 'Ma Huateng',
 'Beate Heister & Karl Albrecht Jr. & family',
 'Giovanni Ferrero',
 'Li Ka-shing',
 'Stephen Schwarzman',
 'Lee Shau Kee',
 'Len Blavatnik',
 'Jacqueline Mars',
 'John Mars',
 'Alain Wertheimer',
 'Gerard Wertheimer',
 'German Larrea Mota Velasco & family',
 'Gina Rinehart',
 'Shiv Nadar',
 'Jim Simons',
 'He Xiangjian',
 'Miriam Adelson & family',
 'Dietrich Mateschitz',
 'Leonardo Del Vecchio & family',
 'Ken Griffin',
 'Tadashi Yanai & family',
 'William Lei Ding',
 'Susanne Klatten',
 'Cyrus Poonawalla',
 'Wang Wei',
 'Qin Yinglin',
 'Sam Bankman-Fried',
 'Takemitsu Takizaki',
 'Li Shufu',
 'Emmanuel Besnier',
 'R. Budi Hartono',
 'Leonard Lauder',
 'Guillaume Pousaz',
 'Iris Fontbona & family',
 'Jack Ma',
 'Michael Hartono',
 'Eric Schmidt',
 'Ray Dalio',
 'Daniel Gilbert',
 'Thomas Frist, Jr. & family',
 'Masayoshi Son',
 'Abigail Johnson',
 'Rupert Murdoch & family',
 'Stefan Quandt',
 'Jensen Huang',
 'Huang Shilin',
 'Thomas Peterffy',
 'Radhakishan Damani',
 'Pang Kang',
 'Wang Chuanfu',
 'Reinhold Wuerth & family',
 'Theo Albrecht, Jr. & family',
 'Yang Huiyan & family',
 'Vladimir Lisin',
 'Fan Hongwei',
 'Lakshmi Mittal',
 'Andrew Forrest',
 'Jiang Rensheng & family',
 'Savitri Jindal & family',
 'Wang Wenyin',
 'Li Xiting',
 'Stefan Persson',
 'Steve Cohen',
 'Vladimir Potanin',
 'Harold Hamm & family',
 'Sun Piaoyang',
 'Luo Liguo & family',
 'Peter Woo',
 'Gianluigi & Rafaela Aponte',
 'David Tepper',
 'Renata Kellnerova & family',
 'John Menard, Jr.',
 'Kumar Birla',
 'Carl Icahn',
 'Hank & Doug Meijer',
 'Lukas Walton',
 'Laurene Powell Jobs & family',
 'James Ratcliffe',
 'Donald Bren',
 'Xu Hang',
 'Lu Xiangyang',
 'Dilip Shanghvi',
 'Wei Jianjun & family',
 'Jorge Paulo Lemann & family',
 'Eyal Ofer',
 'Mike Cannon-Brookes',
 'Wu Yajun',
 'Charlene de Carvalho-Heineken & family',
 'Michael Platt',
 'Pavel Durov',
 'Scott Farquhar',
 'Pallonji Mistry',
 'Dang Yanbao',
 'Robert Pera',
 'Donald Newhouse',
 'Uday Kotak',
 'Aliko Dangote',
 'Leonid Mikhelson',
 'Sunil Mittal & family',
 'Robert & Philip Ng',
 'Liu Hanyuan',
 'Joseph Lau',
 'Anders Holch Povlsen',
 'Dhanin Chearavanont',
 'Gong Hongjia & family',
 'Liu Yongxing',
 'Alexey Mordashov',
 'Wang Jianlin',
 'David Duffield',
 'Li Zhenguo & family',
 'Harry Triguboff',
 'Zhang Zhidong',
 'Chen Bang',
 'John Doerr',
 'Hinduja brothers',
 'Kwong Siu-hing',
 'Pei Zhenhua',
 'Ricardo Salinas Pliego & family',
 'Jim Pattison',
 'Charles Schwab',
 'Goh Cheng Liang',
 'Lin Jianhua',
 'Charoen Sirivadhanabhakdi',
 'Jeff Yass',
 'John Fredriksen',
 'Andreas Struengmann & family',
 'Thomas Struengmann & family',
 'Mikhail Fridman',
 'Sarath Ratanavadi',
 'Robert Kuok',
 'Lei Jun',
 'Zhang Congyuan',
 'Lui Che Woo',
 'Brian Chesky',
 'Israel Englander',
 'Dustin Moskovitz',
 'Alisher Usmanov',
 'Jay Chaudhry',
 'Anthony Pratt',
 'Colin Zheng Huang',
 'Jin Baofang',
 'Pierre Omidyar',
 'Gennady Timchenko',
 'Carl Cook',
 'Andrey Melnichenko',
 'Wang Xing',
 'Philip Anschutz',
 'David Cheriton',
 'Alexander Otto',
 'Diane Hendricks',
 'Stanley Kroenke',
 'Jerry Jones',
 'Quek Leng Chan',
 'Eduardo Saverin',
 'Vagit Alekperov',
 'Richard Liu',
 'Idan Ofer',
 'Melker Schorling & family',
 'Chase Coleman, III.',
 'Shuirong Li',
 'Stefano Pessina',
 'Mikhail Prokhorov',
 'Marcel Herrmann Telles',
 'Leon Black',
 'Joe Gebbia',
 'David Geffen',
 'Yu Renrong']

In [5]:
net = []
w = driver.find_elements(By.XPATH,'//div[@class="netWorth"]')
for i in w:
    net.append(i.text)
net

['$219 B',
 '$171 B',
 '$158 B',
 '$129 B',
 '$118 B',
 '$111 B',
 '$107 B',
 '$106 B',
 '$91.4 B',
 '$90.7 B',
 '$90 B',
 '$82 B',
 '$81.2 B',
 '$74.8 B',
 '$67.3 B',
 '$66.2 B',
 '$65.7 B',
 '$65.3 B',
 '$65 B',
 '$65 B',
 '$60 B',
 '$60 B',
 '$59.6 B',
 '$55.1 B',
 '$50 B',
 '$49.2 B',
 '$47.3 B',
 '$47.1 B',
 '$44.8 B',
 '$43.6 B',
 '$41.4 B',
 '$40.4 B',
 '$37.3 B',
 '$37.2 B',
 '$36.8 B',
 '$36.2 B',
 '$34.8 B',
 '$34.8 B',
 '$32.6 B',
 '$32.5 B',
 '$31.7 B',
 '$31.7 B',
 '$31.2 B',
 '$31.2 B',
 '$30.8 B',
 '$30.2 B',
 '$28.7 B',
 '$28.6 B',
 '$28.3 B',
 '$27.5 B',
 '$27.4 B',
 '$27.3 B',
 '$27.2 B',
 '$26.1 B',
 '$25.2 B',
 '$24.3 B',
 '$24.3 B',
 '$24.3 B',
 '$24.1 B',
 '$24 B',
 '$23.9 B',
 '$23.7 B',
 '$23.5 B',
 '$23.2 B',
 '$23.1 B',
 '$23 B',
 '$22.8 B',
 '$22.8 B',
 '$22.3 B',
 '$22.1 B',
 '$22 B',
 '$22 B',
 '$21.8 B',
 '$21.3 B',
 '$21.2 B',
 '$20.8 B',
 '$20.7 B',
 '$20.6 B',
 '$20.3 B',
 '$20.1 B',
 '$20 B',
 '$19.6 B',
 '$19.5 B',
 '$19 B',
 '$18.7 B',
 '$18.7 B',
 '$18.4 B',
 '$18.2 B',
 '$17.9 B',
 '$17.8 B',
 '$17.7 B',
 '$17.7 B',
 '$17.7 B',
 '$17.6 B',
 '$17.6 B',
 '$17.4 B',
 '$17.3 B',
 '$17.2 B',
 '$17.1 B',
 '$17 B',
 '$17 B',
 '$16.8 B',
 '$16.7 B',
 '$16.6 B',
 '$16.6 B',
 '$16.5 B',
 '$16.5 B',
 '$16.5 B',
 '$16.5 B',
 '$16.4 B',
 '$16.3 B',
 '$16.2 B',
 '$16.1 B',
 '$15.7 B',
 '$15.6 B',
 '$15.5 B',
 '$15.4 B',
 '$15.4 B',
 '$15.3 B',
 '$15.3 B',
 '$15.2 B',
 '$15.2 B',
 '$15.1 B',
 '$15.1 B',
 '$15 B',
 '$14.8 B',
 '$14.6 B',
 '$14.4 B',
 '$14.3 B',
 '$14 B',
 '$14 B',
 '$13.9 B',
 '$13.7 B',
 '$13.65 B',
 '$13.6 B',
 '$13.6 B',
 '$13.5 B',
 '$13.2 B',
 '$13.2 B',
 '$13.2 B',
 '$13.2 B',
 '$12.9 B',
 '$12.9 B',
 '$12.8 B',
 '$12.8 B',
 '$12.7 B',
 '$12.7 B',
 '$12.7 B',
 '$12.6 B',
 '$12.5 B',
 '$12.4 B',
 '$12.2 B',
 '$12.2 B',
 '$12.1 B',
 '$12.1 B',
 '$12 B',
 '$12 B',
 '$11.9 B',
 '$11.9 B',
 '$11.9 B',
 '$11.8 B',
 '$11.8 B',
 '$11.7 B',
 '$11.7 B',
 '$11.7 B',
 '$11.6 B',
 '$11.5 B',
 '$11.5 B',
 '$11.5 B',
 '$11.5 B',
 '$11.4 B',
 '$11.4 B',
 '$11.3 B',
 '$11.3 B',
 '$11.3 B',
 '$11.3 B',
 '$11.1 B',
 '$11.1 B',
 '$11 B',
 '$10.9 B',
 '$10.9 B',
 '$10.9 B',
 '$10.7 B',
 '$10.7 B',
 '$10.6 B',
 '$10.6 B',
 '$10.6 B',
 '$10.5 B',
 '$10.5 B',
 '$10.5 B',
 '$10.4 B',
 '$10.3 B',
 '$10.3 B',
 '$10.3 B',
 '$10.3 B',
 '$10.3 B',
 '$10 B',
 '$10 B',
 '$10 B',
 '$10 B']

In [7]:
country = []
A = driver.find_elements(By.XPATH,'//div[@class="countryOfCitizenship"]')
for i in A:
    country.append(i.text)
country

['United States',
 'United States',
 'France',
 'United States',
 'United States',
 'United States',
 'United States',
 'United States',
 'United States',
 'India',
 'India',
 'United States',
 'Mexico',
 'France',
 'United States',
 'United States',
 'China',
 'United States',
 'United States',
 'Canada',
 'United States',
 'United States',
 'Spain',
 'United States',
 'China',
 'Canada',
 'United States',
 'Germany',
 'Hong Kong',
 'United States',
 'France',
 'France',
 'Germany',
 'China',
 'Germany',
 'Italy',
 'Hong Kong',
 'United States',
 'Hong Kong',
 'United States',
 'United States',
 'United States',
 'France',
 'France',
 'Mexico',
 'Australia',
 'India',
 'United States',
 'China',
 'United States',
 'Austria',
 'Italy',
 'United States',
 'Japan',
 'China',
 'Germany',
 'India',
 'China',
 'China',
 'United States',
 'Japan',
 'China',
 'France',
 'Indonesia',
 'United States',
 'Switzerland',
 'Chile',
 'China',
 'Indonesia',
 'United States',
 'United States',
 'United States',
 'United States',
 'Japan',
 'United States',
 'United States',
 'Germany',
 'United States',
 'China',
 'United States',
 'India',
 'China',
 'China',
 'Germany',
 'Germany',
 'China',
 'Russia',
 'China',
 'India',
 'Australia',
 'China',
 'India',
 'China',
 'Singapore',
 'Sweden',
 'United States',
 'Russia',
 'United States',
 'China',
 'China',
 'Hong Kong',
 'Switzerland',
 'United States',
 'Czechia',
 'United States',
 'India',
 'United States',
 'United States',
 'United States',
 'United States',
 'United Kingdom',
 'United States',
 'Hong Kong',
 'China',
 'India',
 'China',
 'Brazil',
 'Israel',
 'Australia',
 'China',
 'Netherlands',
 'United Kingdom',
 'United Arab Emirates',
 'Australia',
 'Ireland',
 'China',
 'United States',
 'United States',
 'India',
 'Nigeria',
 'Russia',
 'India',
 'Singapore',
 'China',
 'Hong Kong',
 'Denmark',
 'Thailand',
 'Hong Kong',
 'China',
 'Russia',
 'China',
 'United States',
 'China',
 'Australia',
 'China',
 'China',
 'United States',
 'United Kingdom',
 'Hong Kong',
 'China',
 'Mexico',
 'Canada',
 'United States',
 'Singapore',
 'China',
 'Thailand',
 'United States',
 'Cyprus',
 'Germany',
 'Germany',
 'Russia',
 'Thailand',
 'Malaysia',
 'China',
 'Taiwan',
 'Hong Kong',
 'United States',
 'United States',
 'United States',
 'Russia',
 'United States',
 'Australia',
 'China',
 'China',
 'United States',
 'Russia',
 'United States',
 'Russia',
 'China',
 'United States',
 'Canada',
 'Germany',
 'United States',
 'United States',
 'United States',
 'Malaysia',
 'Brazil',
 'Russia',
 'China',
 'Israel',
 'Sweden',
 'United States',
 'China',
 'Monaco',
 'Russia',
 'Brazil',
 'United States',
 'United States',
 'United States',
 'China']

In [8]:
com = []
A = driver.find_elements(By.XPATH,'//span[@class="source-text"]')
for i in A:
    com.append(i.text)
com

['Tesla, SpaceX',
 'Amazon',
 'LVMH',
 'Microsoft',
 'Berkshire Hathaway',
 'Google',
 'Google',
 'software',
 'Microsoft',
 'diversified',
 'infrastructure, commodities',
 'Bloomberg LP',
 'telecom',
 "L'Oréal",
 'Facebook',
 'Walmart',
 'beverages, pharmaceuticals',
 'Walmart',
 'Walmart',
 'cryptocurrency exchange',
 'Koch Industries',
 'Koch Industries',
 'Zara',
 'Dell computers',
 'TikTok',
 'media',
 'Nike',
 'retail',
 'batteries',
 'Amazon',
 'shipping',
 'luxury goods',
 'shipping',
 'internet media',
 'supermarkets',
 'Nutella, chocolates',
 'diversified',
 'investments',
 'real estate',
 'music, chemicals',
 'candy, pet food',
 'candy, pet food',
 'Chanel',
 'Chanel',
 'mining',
 'mining',
 'software services',
 'hedge funds',
 'home appliances',
 'casinos',
 'Red Bull',
 'eyeglasses',
 'hedge funds',
 'fashion retail',
 'online games',
 'BMW, pharmaceuticals',
 'vaccines',
 'package delivery',
 'pig breeding',
 'cryptocurrency exchange',
 'sensors',
 'automobiles',
 'cheese',
 'banking, tobacco',
 'Estee Lauder',
 'fintech',
 'mining',
 'e-commerce',
 'banking, tobacco',
 'Google',
 'hedge funds',
 'Quicken Loans',
 'hospitals',
 'internet, telecom',
 'money management',
 'newspapers, TV network',
 'BMW',
 'semiconductors',
 'batteries',
 'discount brokerage',
 'retail, investments',
 'soy sauce',
 'batteries, automobiles',
 'fasteners',
 "Aldi, Trader Joe's",
 'real estate',
 'steel, transport',
 'petrochemicals',
 'steel',
 'mining',
 'vaccines',
 'steel',
 'mining, copper products',
 'medical devices',
 'H&M',
 'hedge funds',
 'metals',
 'oil & gas',
 'pharmaceuticals',
 'chemicals',
 'real estate',
 'Shipping',
 'hedge funds',
 'finance, telecommunications',
 'home improvement stores',
 'commodities',
 'investments',
 'supermarkets',
 'Walmart',
 'Apple, Disney',
 'chemicals',
 'real estate',
 'medical devices',
 'automobiles, batteries',
 'pharmaceuticals',
 'automobiles',
 'beer',
 'real estate, shipping',
 'software',
 'real estate',
 'Heineken',
 'hedge funds',
 'messaging app',
 'software',
 'construction',
 'coal',
 'wireless networking gear',
 'media',
 'banking',
 'cement, sugar',
 'gas, chemicals',
 'telecom',
 'real estate',
 'agribusiness',
 'real estate',
 'fashion retail',
 'diversified',
 'video surveillance',
 'diversified',
 'steel, investments',
 'real estate',
 'business software',
 'solar wafers and modules',
 'real estate',
 'internet media',
 'hospitals',
 'venture capital',
 'diversified',
 'real estate',
 'batteries',
 'retail, media',
 'diversified',
 'discount brokerage',
 'paints',
 'solar panel components',
 'alcohol, real estate',
 'trading, investments',
 'shipping',
 'pharmaceuticals',
 'pharmaceuticals',
 'oil, banking, telecom',
 'energy',
 'palm oil, shipping, property',
 'smartphones',
 'shoes',
 'casinos/hotels',
 'Airbnb',
 'hedge funds',
 'Facebook',
 'steel, telecom, investments',
 'security software',
 'manufacturing',
 'e-commerce',
 'solar panels',
 'eBay, PayPal',
 'oil, gas',
 'medical devices',
 'coal, fertilizers',
 'e-commerce',
 'investments',
 'Google',
 'real estate',
 'roofing',
 'sports, real estate',
 'Dallas Cowboys',
 'banking, property',
 'Facebook',
 'oil',
 'e-commerce',
 'shipping',
 'investments',
 'investments',
 'petrochemicals',
 'drugstores',
 'investments',
 'beer',
 'private equity',
 'Airbnb',
 'movies, record labels',
 'semiconductors']

In [10]:
age = []
A = driver.find_elements(By.XPATH,'//div[@class="age"]')
for i in A:
    age.append(i.text)
age

['50',
 '58',
 '73',
 '66',
 '91',
 '49',
 '48',
 '77',
 '66',
 '64',
 '59',
 '80',
 '82',
 '68',
 '37',
 '73',
 '67',
 '72',
 '77',
 '44',
 '86',
 '59',
 '86',
 '57',
 '38',
 '64',
 '84',
 '82',
 '53',
 '51',
 '52',
 '85',
 '84',
 '50',
 'N/A',
 '57',
 '93',
 '75',
 '94',
 '64',
 '82',
 '86',
 '73',
 '71',
 '68',
 '68',
 '76',
 '83',
 '79',
 '76',
 '77',
 '86',
 '53',
 '73',
 '50',
 '59',
 '80',
 '51',
 '56',
 '30',
 '76',
 '58',
 '51',
 '81',
 '89',
 '40',
 '79',
 '57',
 '82',
 '66',
 '72',
 '60',
 '83',
 '64',
 '60',
 '91',
 '55',
 '59',
 '55',
 '77',
 '67',
 '66',
 '56',
 '86',
 '71',
 '40',
 '65',
 '55',
 '71',
 '60',
 '68',
 '72',
 '54',
 '71',
 '74',
 '65',
 '61',
 '76',
 '63',
 '66',
 '75',
 '81',
 '64',
 '54',
 '82',
 '54',
 '86',
 'N/A',
 '35',
 '58',
 '69',
 '89',
 '55',
 '59',
 '66',
 '58',
 '82',
 '71',
 '42',
 '58',
 '67',
 '54',
 '37',
 '42',
 '92',
 '49',
 '44',
 '92',
 '63',
 '64',
 '66',
 '64',
 'N/A',
 '58',
 '70',
 '49',
 '82',
 '57',
 '73',
 '56',
 '67',
 '81',
 '54',
 '89',
 '50',
 '56',
 '70',
 'N/A',
 '92',
 '63',
 '66',
 '93',
 '84',
 '94',
 '59',
 '77',
 '63',
 '77',
 '72',
 '72',
 '57',
 '56',
 '98',
 '52',
 '74',
 '93',
 '40',
 '73',
 '37',
 '68',
 '62',
 '61',
 '42',
 '69',
 '54',
 '69',
 '59',
 '50',
 '43',
 '82',
 '71',
 '54',
 '75',
 '74',
 '79',
 '80',
 '40',
 '71',
 '48',
 '66',
 '74',
 '46',
 '65',
 '80',
 '56',
 '72',
 '70',
 '40',
 '79',
 '56']

In [13]:
B = pd.DataFrame()
B['NAME'] = name
B['AGE'] = age
B['COUNTRY']=country
B['INDUSTRY'] = com
B['NET WORTH']=net
B

                         NAME AGE        COUNTRY INDUSTRY NET WORTH
0                   Elon Musk      United States       50    $219 B
1                  Jeff Bezos      United States       58    $171 B
2    Bernard Arnault & family             France       73    $158 B
3                  Bill Gates      United States       66    $129 B
4              Warren Buffett      United States       91    $118 B
..                        ...  ..            ...      ...       ...
195    Marcel Herrmann Telles             Brazil       72   $10.3 B
196                Leon Black      United States       70     $10 B
197                Joe Gebbia      United States       40     $10 B
198              David Geffen      United States       79     $10 B
199                Yu Renrong              China       56     $10 B

[200 rows x 5 columns]

In [2]:
driver = webdriver.Chrome(r'C:\Users\prasad kalekar\Selenium\chromedriver.exe')
driver.maximize_window()
driver = webdriver.Chrome('chromedriver.exe')
url = 'https://www.hostelworld.com/'

driver.get(url)

In [3]:
name = []
N = driver.find_elements(By.XPATH,'//h2[@class="title title-6"]')
for i in N:
    name.append(i.text)
name

["Wombat's City Hostel London",
 "St Christopher's Village",
 'Generator London',
 'Safestay London Elephant & Castle',
 'Hostel One Notting Hill',
 'Urbany Hostel London',
 'Safestay London Kensington Holland Park',
 'No.8 Willesden Hostel London',
 'Astor Museum Inn',
 'Phoenix Hostel',
 'Smart Camden Inn Hostel',
 "St Christopher's Camden",
 'No.8 Seven Sisters',
 'Smart Hyde Park Inn Hostel',
 'NX London Hostel',
 "St Christopher's Hammersmith",
 'London Backpackers',
 'Destinations Hostels @ The Gallery',
 'Barmy Badger Backpackers',
 'Astor Victoria',
 'YHA London Oxford Street',
 'Pickwick Hall',
 'Queen Elizabeth Chelsea',
 'Prime Backpackers Angel',
 'Dover Castle Hostel and Bar',
 "St Christopher's Inn - Liverpool Street",
 'Astor Kensington',
 'Saint James Backpackers',
 'Kensal Green Backpackers',
 "St Christopher's Shepherds Bush"]

In [5]:
distance = []
N = driver.find_elements(By.XPATH,'//span[@class="description"]')
for i in N:
    distance.append(i.text)
distance

['Hostel - 3.6km from city centre',
 'Hostel - 1.8km from city centre',
 'Hostel - 3km from city centre',
 'Hostel - 1.7km from city centre',
 'Hostel - 5.5km from city centre',
 'Hostel - 5.4km from city centre',
 'Hostel - 5.9km from city centre',
 'Hostel - 10km from city centre',
 'Hostel - 2.2km from city centre',
 'Hostel - 4.2km from city centre',
 'Hostel - 4.4km from city centre',
 'Hostel - 4.3km from city centre',
 'Hostel - 9km from city centre',
 'Hostel - 5km from city centre',
 'Hostel - 6.1km from city centre',
 'Hostel - 7.5km from city centre',
 'Hostel - 11.9km from city centre',
 'Hostel - 1.7km from city centre',
 'Hostel - 5.5km from city centre',
 'Hostel - 1.8km from city centre',
 'Hostel - 2.1km from city centre',
 'Hostel - 2.3km from city centre',
 'Hostel - 5.7km from city centre',
 'Hostel - 3.6km from city centre',
 'Hostel - 1.7km from city centre',
 'Hostel - 3.2km from city centre',
 'Hostel - 4.9km from city centre',
 'Hostel - 5.5km from city centre',
 'Hostel - 8.2km from city centre',
 'Hostel - 7km from city centre']

In [6]:
ratings = []
N = driver.find_elements(By.XPATH,'//div[@class="rating rating-summary-container big"]')
for i in N:
    ratings.append(i.text)
ratings

['9.0\nSuperb\n14308 Total Reviews',
 '8.1\nFabulous\n11679 Total Reviews',
 '7.7\nVery Good\n7255 Total Reviews',
 '7.1\nVery Good\n4663 Total Reviews',
 '9.3\nSuperb\n1587 Total Reviews',
 '9.2\nSuperb\n537 Total Reviews',
 '6.8\nGood\n1374 Total Reviews',
 '6.8\nGood\n4886 Total Reviews',
 '8.1\nFabulous\n9110 Total Reviews',
 '7.1\nVery Good\n3855 Total Reviews',
 '8.3\nFabulous\n2975 Total Reviews',
 '8.3\nFabulous\n3895 Total Reviews',
 '5.4\nRating\n3907 Total Reviews',
 '7.4\nVery Good\n6420 Total Reviews',
 '7.5\nVery Good\n1339 Total Reviews',
 '7.8\nVery Good\n4156 Total Reviews',
 '7.9\nVery Good\n4370 Total Reviews',
 '9.4\nSuperb\n75 Total Reviews',
 '8.9\nFabulous\n1854 Total Reviews',
 '7.7\nVery Good\n14853 Total Reviews',
 '8.8\nFabulous\n4602 Total Reviews',
 '8.4\nFabulous\n2513 Total Reviews',
 '7.1\nVery Good\n3356 Total Reviews',
 '8.2\nFabulous\n683 Total Reviews',
 '8.3\nFabulous\n2293 Total Reviews',
 '8.3\nFabulous\n444 Total Reviews',
 '8.0\nFabulous\n6443 Total Reviews',
 '7.3\nVery Good\n1845 Total Reviews',
 '5.0\nRating\n3667 Total Reviews',
 '7.4\nVery Good\n730 Total Reviews']

In [7]:
B = pd.DataFrame()
B['HOTEL NAME'] = name
B['DISTANCE FROM CITY CENTRE'] = distance
B['RATINGS']=ratings
B

,HOTEL NAME,DISTANCE FROM CITY CENTRE,RATINGS
0,Wombat's City Hostel London,Hostel - 3.6km from city centre,9.0\nSuperb\n14308 Total Reviews
1,St Christopher's Village,Hostel - 1.8km from city centre,8.1\nFabulous\n11679 Total Reviews
2,Generator London,Hostel - 3km from city centre,7.7\nVery Good\n7255 Total Reviews
3,Safestay London Elephant & Castle,Hostel - 1.7km from city centre,7.1\nVery Good\n4663 Total Reviews
4,Hostel One Notting Hill,Hostel - 5.5km from city centre,9.3\nSuperb\n1587 Total Reviews
5,Urbany Hostel London,Hostel - 5.4km from city centre,9.2\nSuperb\n537 Total Reviews
6,Safestay London Kensington Holland Park,Hostel - 5.9km from city centre,6.8\nGood\n1374 Total Reviews
7,No.8 Willesden Hostel London,Hostel - 10km from city centre,6.8\nGood\n4886 Total Reviews
8,Astor Museum Inn,Hostel - 2.2km from city centre,8.1\nFabulous\n9110 Total Reviews
9,Phoenix Hostel,Hostel - 4.2km from city centre,7.1\nVery Good\n3855 Total Reviews
10,Smart Camden Inn Hostel,Hostel - 4.4km from city centre,8.3\nFabulous\n2975 Total Reviews
11,St Christopher's Camden,Hostel - 4.3km from city centre,8.3\nFabulous\n3895 Total Reviews
12,No.8 Seven Sisters,Hostel - 9km from city centre,5.4\nRating\n3907 Total Reviews
13,Smart Hyde Park Inn Hostel,Hostel - 5km from city centre,7.4\nVery Good\n6420 Total Reviews
14,NX London Hostel,Hostel - 6.1km from city centre,7.5\nVery Good\n1339 Total Reviews
15,St Christopher's Hammersmith,Hostel - 7.5km from city centre,7.8\nVery Good\n4156 Total Reviews
16,London Backpackers,Hostel - 11.9km from city centre,7.9\nVery Good\n4370 Total Reviews
17,Destinations Hostels @ The Gallery,Hostel - 1.7km from city centre,9.4\nSuperb\n75 Total Reviews
18,Barmy Badger Backpackers,Hostel - 5.5km from city centre,8.9\nFabulous\n1854 Total Reviews
19,Astor Victoria,Hostel - 1.8km from city centre,7.7\nVery Good\n14853 Total Reviews
20,YHA London Oxford Street,Hostel - 2.1km from city centre,8.8\nFabulous\n4602 Total Reviews
21,Pickwick Hall,Hostel - 2.3km from city centre,8.4\nFabulous\n2513 Total Reviews
22,Queen Elizabeth Chelsea,Hostel - 5.7km from city centre,7.1\nVery Good\n3356 Total Reviews
23,Prime Backpackers Angel,Hostel - 3.6km from city centre,8.2\nFabulous\n683 Total Reviews
24,Dover Castle Hostel and Bar,Hostel - 1.7km from city centre,8.3\nFabulous\n2293 Total Reviews
25,St Christopher's Inn - Liverpool Street,Hostel - 3.2km from city centre,8.3\nFabulous\n444 Total Reviews
26,Astor Kensington,Hostel - 4.9km from city centre,8.0\nFabulous\n6443 Total Reviews
27,Saint James Backpackers,Hostel - 5.5km from city centre,7.3\nVery Good\n1845 Total Reviews
28,Kensal Green Backpackers,Hostel - 8.2km from city centre,5.0\nRating\n3667 Total Reviews
29,St Christopher's Shepherds Bush,Hostel - 7km from city centre,7.4\nVery Good\n730 Total Reviews

In [8]:
driver = webdriver.Chrome(r'C:\Users\prasad kalekar\Selenium\chromedriver.exe')
driver.maximize_window()
driver = webdriver.Chrome('chromedriver.exe')
url = ' digit.in'

driver.get(url)

InvalidArgumentException: Message: invalid argument
  (Session info: chrome=107.0.5304.107)
Stacktrace:
Backtrace:
	Ordinal0 [0x00E1ACD3+2075859]
	Ordinal0 [0x00DAEE61+1633889]
	Ordinal0 [0x00CAB680+571008]
	Ordinal0 [0x00C9E8FE+518398]
	Ordinal0 [0x00C9D2A3+512675]
	Ordinal0 [0x00C9D5AD+513453]
	Ordinal0 [0x00CAD0CE+577742]
	Ordinal0 [0x00D0BC7D+965757]
	Ordinal0 [0x00CF731C+881436]
	Ordinal0 [0x00D0B56A+963946]
	Ordinal0 [0x00CF7136+880950]
	Ordinal0 [0x00CCFEFD+720637]
	Ordinal0 [0x00CD0F3F+724799]
	GetHandleVerifier [0x010CEED2+2769538]
	GetHandleVerifier [0x010C0D95+2711877]
	GetHandleVerifier [0x00EAA03A+521194]
	GetHandleVerifier [0x00EA8DA0+516432]
	Ordinal0 [0x00DB682C+1665068]
	Ordinal0 [0x00DBB128+1683752]
	Ordinal0 [0x00DBB215+1683989]
	Ordinal0 [0x00DC6484+1729668]
	BaseThreadInitThunk [0x75DAFEF9+25]
	RtlGetAppContainerNamedObjectPath [0x77DD7BBE+286]
	RtlGetAppContainerNamedObjectPath [0x77DD7B8E+238]

In [9]:
driver = webdriver.Chrome(r'C:\Users\prasad kalekar\Selenium\chromedriver.exe')
driver.maximize_window()
driver = webdriver.Chrome('chromedriver.exe')
url = 'https://www.youtube.com/'

driver.get(url)

In [10]:
comments = []
N = driver.find_elements(By.XPATH,'//div[@class="style-scope ytd-comment-renderer"]')
for i in N:
    comments.append(i.text)
comments

['',
 '',
 'Pinned by Sony Music India\nSoulful Arijit Singh\n4 months ago\nKesariya \n163K\nReply',
 '',
 'Pinned by Sony Music India\nSoulful Arijit Singh\n4 months ago\nKesariya \n163K\nReply',
 'Pinned by Sony Music India\nSoulful Arijit Singh\n4 months ago',
 'Pinned by Sony Music India',
 'Soulful Arijit Singh\n4 months ago',
 'Kesariya ',
 '',
 '',
 '',
 '',
 "Sifat Ahsan\n3 months ago\nEven if you have never fallen in love, you are bound to fall in love with Arijit Singh's voice\n607\nReply",
 '',
 "Sifat Ahsan\n3 months ago\nEven if you have never fallen in love, you are bound to fall in love with Arijit Singh's voice\n607\nReply",
 'Sifat Ahsan\n3 months ago',
 '',
 'Sifat Ahsan\n3 months ago',
 "Even if you have never fallen in love, you are bound to fall in love with Arijit Singh's voice",
 '',
 '',
 '',
 '',
 "Ram_Charan_Fc\n22 hours ago\nU Can Ignore Bollywood Movies , But U Can't Ignore Arijit Singh Voice ️\n39\nReply",
 '',
 "Ram_Charan_Fc\n22 hours ago\nU Can Ignore Bollywood Movies , But U Can't Ignore Arijit Singh Voice ️\n39\nReply",
 'Ram_Charan_Fc\n22 hours ago',
 '',
 'Ram_Charan_Fc\n22 hours ago',
 "U Can Ignore Bollywood Movies , But U Can't Ignore Arijit Singh Voice ️",
 '',
 '',
 '',
 '',
 'UJJWAL GAMER FANCLUB\n2 days ago\nArijit Singh is the Kohinoor of the indian music industry. His voice will be remembered by generations to come.♡\n65\nReply',
 '',
 'UJJWAL GAMER FANCLUB\n2 days ago\nArijit Singh is the Kohinoor of the indian music industry. His voice will be remembered by generations to come.♡\n65\nReply',
 'UJJWAL GAMER FANCLUB\n2 days ago',
 '',
 'UJJWAL GAMER FANCLUB\n2 days ago',
 'Arijit Singh is the Kohinoor of the indian music industry. His voice will be remembered by generations to come.♡',
 '',
 '',
 '',
 '',
 "muzafir khan. m13\n1 day ago\nEvery Bollywood movie is incomplete without Arijit Singh's song ️ Luv from Jammu and Kashmir \n20\nReply",
 '',
 "muzafir khan. m13\n1 day ago\nEvery Bollywood movie is incomplete without Arijit Singh's song ️ Luv from Jammu and Kashmir \n20\nReply",
 'muzafir khan. m13\n1 day ago',
 '',
 'muzafir khan. m13\n1 day ago',
 "Every Bollywood movie is incomplete without Arijit Singh's song ️ Luv from Jammu and Kashmir ",
 '',
 '',
 '',
 '',
 'Ahmad Akbar\n2 days ago\nMy wife died 2 months ago and this song gives me some great vibes and takes me back to the incredible time we spent back together. I missed her yesterday,i miss her today and will miss her beyond. We were just two years into our marriage. May her soul rest in peace and thanks to Arijit specifically\n146\nReply',
 '',
 'Ahmad Akbar\n2 days ago\nMy wife died 2 months ago and this song gives me some great vibes and takes me back to the incredible time we spent back together. I missed her yesterday,i miss her today and will miss her beyond. We were just two years into our marriage. May her soul rest in peace and thanks to Arijit specifically\n146\nReply',
 'Ahmad Akbar\n2 days ago',
 '',
 'Ahmad Akbar\n2 days ago',
 'My wife died 2 months ago and this song gives me some great vibes and takes me back to the incredible time we spent back together. I missed her yesterday,i miss her today and will miss her beyond. We were just two years into our marriage. May her soul rest in peace and thanks to Arijit specifically',
 '',
 '',
 '',
 '',
 'harvir singh\n2 days ago\nAs a Banarasi, it feels very lovely that this song is fully shot in Banaras. The beauty of Banaras, The Ghats, The Vishwanath temple, the Boats, The Diyas, The Galliyan, The Ganga Maiyya, The People and The Love of Shiva-Isha  has been captured beautifully in this song.\n\nLots of love to Ayan Mukerji and team \n18\nReply',
 '',
 'harvir singh\n2 days ago\nAs a Banarasi, it feels very lovely that this song is fully shot in Banaras. The beauty of Banaras, The Ghats, The Vishwanath temple, the Boats, The Diyas, The Galliyan, The Ganga Maiyya, The People and The Love of Shiva-Isha  has been captured beautifully in this song.\n\nLots of love to Ayan Mukerji and team \n18\nReply',
 'harvir singh\n2 days ago',
 '',
 'harvir singh\n2 days ago',
 'As a Banarasi, it feels very lovely that this song is fully shot in Banaras. The beauty of Banaras, The Ghats, The Vishwanath temple, the Boats, The Diyas, The Galliyan, The Ganga Maiyya, The People and The Love of Shiva-Isha  has been captured beautifully in this song.\n\nLots of love to Ayan Mukerji and team ',
 '',
 '',
 '',
 '',
 "Neetesh Zung\n4 months ago\nSong doesn't matter, Arijit's voice matters ️\n864\nReply",
 '',
 "Neetesh Zung\n4 months ago\nSong doesn't matter, Arijit's voice matters ️\n864\nReply",
 'Neetesh Zung\n4 months ago',
 '',
 'Neetesh Zung\n4 months ago',
 "Song doesn't matter, Arijit's voice matters ️",
 '',
 '',
 '',
 '',
 'яєναтι .......\n5 days ago (edited)\nBest song Ever \nArjit singh is very talented  person and his voice is very soulful  \nArjit singh is the best singer ever ️\n134\nReply',
 '',
 'яєναтι .......\n5 days ago (edited)\nBest song Ever \nArjit singh is very talented  person and his voice is very soulful  \nArjit singh is the best singer ever ️\n134\nReply',
 'яєναтι .......\n5 days ago (edited)',
 '',
 'яєναтι .......\n5 days ago (edited)',
 'Best song Ever \nArjit singh is very talented  person and his voice is very soulful  \nArjit singh is the best singer ever ️',
 '',
 '',
 '',
 '',
 '190_SUYASH PANDEY\n8 days ago\nNo matter what is the lyrics he can give you the best out of it that is our Arijit sir !\n76\nReply',
 '',
 '190_SUYASH PANDEY\n8 days ago\nNo matter what is the lyrics he can give you the best out of it that is our Arijit sir !\n76\nReply',
 '190_SUYASH PANDEY\n8 days ago',
 '',
 '190_SUYASH PANDEY\n8 days ago',
 'No matter what is the lyrics he can give you the best out of it that is our Arijit sir !',
 '',
 '',
 '',
 '',
 "Aditya Joshi\n7 days ago (edited)\nKesariya is not just a song, it is a melodious emotion ️...\nArijit Singh's voice is incomparable \n33\nReply",
 '',
 "Aditya Joshi\n7 days ago (edited)\nKesariya is not just a song, it is a melodious emotion ️...\nArijit Singh's voice is incomparable \n33\nReply",
 'Aditya Joshi\n7 days ago (edited)',
 '',
 'Aditya Joshi\n7 days ago (edited)',
 "Kesariya is not just a song, it is a melodious emotion ️...\nArijit Singh's voice is incomparable ",
 '',
 '',
 '',
 '',
 'Dhiraj Mahajan\n4 days ago\nSuperb song \n5\nReply',
 '',
 'Dhiraj Mahajan\n4 days ago\nSuperb song \n5\nReply',
 'Dhiraj Mahajan\n4 days ago',
 '',
 'Dhiraj Mahajan\n4 days ago',
 'Superb song ',
 '',
 '',
 '',
 '',
 'Tasmia Mir\n4 months ago (edited)\nThis song released when Arijit was doing concert in Sydney. We were there , his voice without instruments 100% same. He is extremely talented and amazing human. ️\n793\nReply',
 '',
 'Tasmia Mir\n4 months ago (edited)\nThis song released when Arijit was doing concert in Sydney. We were there , his voice without instruments 100% same. He is extremely talented and amazing human. ️\n793\nReply',
 'Tasmia Mir\n4 months ago (edited)',
 '',
 'Tasmia Mir\n4 months ago (edited)',
 'This song released when Arijit was doing concert in Sydney. We were there , his voice without instruments 100% same. He is extremely talented and amazing human. ️',
 '',
 '',
 '',
 '',
 "New hindi songs\n2 days ago\nThere is only one person can save Bollywood's melodies song that is Arijit Singh !! \n55\nReply",
 '',
 "New hindi songs\n2 days ago\nThere is only one person can save Bollywood's melodies song that is Arijit Singh !! \n55\nReply",
 'New hindi songs\n2 days ago',
 '',
 'New hindi songs\n2 days ago',
 "There is only one person can save Bollywood's melodies song that is Arijit Singh !! ",
 '',
 '',
 '',
 '',
 'Lathika Anand\n10 days ago\nI am crazy for this beautiful song.Hearing more than 5 times daily ️️\n166\nReply',
 '',
 'Lathika Anand\n10 days ago\nI am crazy for this beautiful song.Hearing more than 5 times daily ️️\n166\nReply',
 'Lathika Anand\n10 days ago',
 '',
 'Lathika Anand\n10 days ago',
 'I am crazy for this beautiful song.Hearing more than 5 times daily ️️',
 '',
 '',
 '',
 '',
 "New Hindi Songs 🧡\n3 days ago\nI don't know why Arijit Singh makes me feel like I lost someone who i've never had \n41\nReply",
 '',
 "New Hindi Songs 🧡\n3 days ago\nI don't know why Arijit Singh makes me feel like I lost someone who i've never had \n41\nReply",
 'New Hindi Songs 🧡\n3 days ago',
 '',
 'New Hindi Songs 🧡\n3 days ago',
 "I don't know why Arijit Singh makes me feel like I lost someone who i've never had ",
 '',
 '',
 '',
 '',
 "100K subs without video challenge.\n2 days ago\nI'm like an asthma patient, and Arijit Singh songs are like Inhaler for me. \n\nI can't live without this \n38\nReply",
 '',
 "100K subs without video challenge.\n2 days ago\nI'm like an asthma patient, and Arijit Singh songs are like Inhaler for me. \n\nI can't live without this \n38\nReply",
 '100K subs without video challenge.\n2 days ago',
 '',
 '100K subs without video challenge.\n2 days ago',
 "I'm like an asthma patient, and Arijit Singh songs are like Inhaler for me. \n\nI can't live without this ",
 '',
 '',
 '',
 '',
 'subho💫\n4 days ago\ni am single,  but when i hear this types of songs, then i feel i am in love. This is power of music \n60\nReply',
 '',
 'subho💫\n4 days ago\ni am single,  but when i hear this types of songs, then i feel i am in love. This is power of music \n60\nReply',
 'subho💫\n4 days ago',
 '',
 'subho💫\n4 days ago',
 'i am single,  but when i hear this types of songs, then i feel i am in love. This is power of music ',
 '',
 '',
 '',
 '',
 'Mandip Roy\n4 months ago\nThe man who never disappoint us and delivers. One of the finest ever, no controversy, just pure talent. Ladies and gentlemen, this is Arijit Singh for you. ️️️\n357\nReply',
 '',
 'Mandip Roy\n4 months ago\nThe man who never disappoint us and delivers. One of the finest ever, no controversy, just pure talent. Ladies and gentlemen, this is Arijit Singh for you. ️️️\n357\nReply',
 'Mandip Roy\n4 months ago',
 '',
 'Mandip Roy\n4 months ago',
 'The man who never disappoint us and delivers. One of the finest ever, no controversy, just pure talent. Ladies and gentlemen, this is Arijit Singh for you. ️️️',
 '',
 '',
 '',
 '',
 'Hindi Hits Love 💕\n8 days ago\nArijit Singh is not only a singer he is an emotional of billion people No words for Arijit Singh voice Just amazing\n133\nReply',
 '',
 'Hindi Hits Love 💕\n8 days ago\nArijit Singh is not only a singer he is an emotional of billion people No words for Arijit Singh voice Just amazing\n133\nReply',
 'Hindi Hits Love 💕\n8 days ago',
 '',
 'Hindi Hits Love 💕\n8 days ago',
 'Arijit Singh is not only a singer he is an emotional of billion people No words for Arijit Singh voice Just amazing',
 '',
 '']

In [11]:
B = pd.DataFrame()
B['YOUTUBE COMMENTS'] = comments
B

                                      YOUTUBE COMMENTS
0
1
2    Pinned by Sony Music India\nSoulful Arijit Sin...
3
4    Pinned by Sony Music India\nSoulful Arijit Sin...
..                                                 ...
215
216                      Hindi Hits Love 💕\n8 days ago
217  Arijit Singh is not only a singer he is an emo...
218
219

[220 rows x 1 columns]

In [12]:
driver = webdriver.Chrome(r'C:\Users\prasad kalekar\Selenium\chromedriver.exe')
driver.maximize_window()
driver = webdriver.Chrome('chromedriver.exe')
url = 'https://www.flipkart.com/'

driver.get(url)

In [13]:
name = []
N = driver.find_elements(By.XPATH,'//div[@class="_4rR01T"]')
for i in N:
    name.append(i.text)
name

['OnePlus Nord 2T 5G (Jade Fog, 256 GB)',
 'OnePlus Nord CE 2 Lite 5G (Black Dusk, 128 GB)',
 'OnePlus Nord CE 2 Lite 5G (Blue Tide, 128 GB)',
 'OnePlus Nord CE 2 Lite 5G (Black Dusk, 128 GB)',
 'OnePlus Nord CE 2 Lite 5G (Blue Tide, 128 GB)',
 'OnePlus Nord CE 2 Lite 5G (Black Dusk, 128 GB)',
 'OnePlus Nord CE 2 Lite 5G (Black Dusk, 128 GB)',
 'OnePlus Nord 2T 5G (Gray Shadow, 256 GB)',
 'OnePlus Nord 2T 5G (Jade Fog, 256 GB)',
 'OnePlus Nord 2T 5G (Jade Fog, 128 GB)',
 'OnePlus Nord 2T 5G (Gray Shadow, 128 GB)',
 'OnePlus Nord CE 2 5G (Bahama Blue, 128 GB)',
 'OnePlus Nord 2T 5G (Gray Shadow, 128 GB)',
 'OnePlus Nord 2T 5G (Jade Fog, 128 GB)',
 'OnePlus Nord 2T 5G (Gray Shadow, 256 GB)',
 'OnePlus Nord 2T 5G (Gray Shadow, 128 GB)',
 'OnePlus Nord 2T 5G (Gray Shadow, 256 GB)',
 'OnePlus Nord CE 2 Lite 5G (Blue Tide, 128 GB)',
 'OnePlus Nord CE 2 Lite 5G (Blue Tide, 128 GB)',
 'OnePlus Nord 2T 5G (Jade Fog, 128 GB)',
 'OnePlus Nord 2T 5G (Gray Shadow, 256 GB)',
 'OnePlus Nord 2T 5G (Jade Fog, 256 GB)',
 'OnePlus Nord CE 2 5G (Bahama Blue, 128 GB)',
 'OnePlus Nord 2T 5G (Jade Fog, 256 GB)']

In [14]:
price = []
N = driver.find_elements(By.XPATH,'//div[@class="_30jeq3 _1_WHN1"]')
for i in N:
    price.append(i.text)
price

['₹33,899',
 '₹19,990',
 '₹19,737',
 '₹19,974',
 '₹19,645',
 '₹19,990',
 '₹19,999',
 '₹33,998',
 '₹33,962',
 '₹28,998',
 '₹28,999',
 '₹24,998',
 '₹29,899',
 '₹28,999',
 '₹33,860',
 '₹28,998',
 '₹33,860',
 '₹19,847',
 '₹19,928',
 '₹28,970',
 '₹33,999',
 '₹33,799',
 '₹24,999',
 '₹33,990']

In [15]:
R = []
N = driver.find_elements(By.XPATH,'//span[@class="_2_R_DZ"]')
for i in N:
    R.append(i.text)
R

['1,461 Ratings & 115 Reviews',
 '31,795 Ratings & 2,696 Reviews',
 '31,795 Ratings & 2,696 Reviews',
 '31,795 Ratings & 2,696 Reviews',
 '31,795 Ratings & 2,696 Reviews',
 '31,795 Ratings & 2,696 Reviews',
 '31,795 Ratings & 2,696 Reviews',
 '1,461 Ratings & 115 Reviews',
 '1,461 Ratings & 115 Reviews',
 '3,828 Ratings & 392 Reviews',
 '3,828 Ratings & 392 Reviews',
 '2,031 Ratings & 207 Reviews',
 '3,828 Ratings & 392 Reviews',
 '3,828 Ratings & 392 Reviews',
 '1,461 Ratings & 115 Reviews',
 '3,828 Ratings & 392 Reviews',
 '1,461 Ratings & 115 Reviews',
 '31,795 Ratings & 2,696 Reviews',
 '31,795 Ratings & 2,696 Reviews',
 '3,828 Ratings & 392 Reviews',
 '1,461 Ratings & 115 Reviews',
 '1,461 Ratings & 115 Reviews',
 '2,031 Ratings & 207 Reviews',
 '1,461 Ratings & 115 Reviews']

In [17]:
B = pd.DataFrame()
B['BRAND'] = name
B['PRICE'] = price
B['RATINGS AND REVIEW']=R
B

,BRAND,PRICE,RATINGS AND REVIEW
0,"OnePlus Nord 2T 5G (Jade Fog, 256 GB)","₹33,899","1,461 Ratings & 115 Reviews"
1,"OnePlus Nord CE 2 Lite 5G (Black Dusk, 128 GB)","₹19,990","31,795 Ratings & 2,696 Reviews"
2,"OnePlus Nord CE 2 Lite 5G (Blue Tide, 128 GB)","₹19,737","31,795 Ratings & 2,696 Reviews"
3,"OnePlus Nord CE 2 Lite 5G (Black Dusk, 128 GB)","₹19,974","31,795 Ratings & 2,696 Reviews"
4,"OnePlus Nord CE 2 Lite 5G (Blue Tide, 128 GB)","₹19,645","31,795 Ratings & 2,696 Reviews"
5,"OnePlus Nord CE 2 Lite 5G (Black Dusk, 128 GB)","₹19,990","31,795 Ratings & 2,696 Reviews"
6,"OnePlus Nord CE 2 Lite 5G (Black Dusk, 128 GB)","₹19,999","31,795 Ratings & 2,696 Reviews"
7,"OnePlus Nord 2T 5G (Gray Shadow, 256 GB)","₹33,998","1,461 Ratings & 115 Reviews"
8,"OnePlus Nord 2T 5G (Jade Fog, 256 GB)","₹33,962","1,461 Ratings & 115 Reviews"
9,"OnePlus Nord 2T 5G (Jade Fog, 128 GB)","₹28,998","3,828 Ratings & 392 Reviews"
10,"OnePlus Nord 2T 5G (Gray Shadow, 128 GB)","₹28,999","3,828 Ratings & 392 Reviews"
11,"OnePlus Nord CE 2 5G (Bahama Blue, 128 GB)","₹24,998","2,031 Ratings & 207 Reviews"
12,"OnePlus Nord 2T 5G (Gray Shadow, 128 GB)","₹29,899","3,828 Ratings & 392 Reviews"
13,"OnePlus Nord 2T 5G (Jade Fog, 128 GB)","₹28,999","3,828 Ratings & 392 Reviews"
14,"OnePlus Nord 2T 5G (Gray Shadow, 256 GB)","₹33,860","1,461 Ratings & 115 Reviews"
15,"OnePlus Nord 2T 5G (Gray Shadow, 128 GB)","₹28,998","3,828 Ratings & 392 Reviews"
16,"OnePlus Nord 2T 5G (Gray Shadow, 256 GB)","₹33,860","1,461 Ratings & 115 Reviews"
17,"OnePlus Nord CE 2 Lite 5G (Blue Tide, 128 GB)","₹19,847","31,795 Ratings & 2,696 Reviews"
18,"OnePlus Nord CE 2 Lite 5G (Blue Tide, 128 GB)","₹19,928","31,795 Ratings & 2,696 Reviews"
19,"OnePlus Nord 2T 5G (Jade Fog, 128 GB)","₹28,970","3,828 Ratings & 392 Reviews"
20,"OnePlus Nord 2T 5G (Gray Shadow, 256 GB)","₹33,999","1,461 Ratings & 115 Reviews"
21,"OnePlus Nord 2T 5G (Jade Fog, 256 GB)","₹33,799","1,461 Ratings & 115 Reviews"
22,"OnePlus Nord CE 2 5G (Bahama Blue, 128 GB)","₹24,999","2,031 Ratings & 207 Reviews"
23,"OnePlus Nord 2T 5G (Jade Fog, 256 GB)","₹33,990","1,461 Ratings & 115 Reviews"

In [18]:
name = []
N = driver.find_elements(By.XPATH,'//div[@class="_4rR01T"]')
for i in N:
    name.append(i.text)
name

['Google Pixel 4a (Just Black, 128 GB)',
 'vivo T1 44W (Starry Sky, 128 GB)',
 'vivo T1 44W (Midnight Galaxy, 128 GB)',
 'vivo T1 44W (Starry Sky, 128 GB)',
 'vivo T1 44W (Ice Dawn, 128 GB)',
 'vivo T1 44W (Ice Dawn, 128 GB)',
 'vivo T1 44W (Midnight Galaxy, 128 GB)',
 'vivo T1 44W (Midnight Galaxy, 128 GB)',
 'vivo T1 44W (Starry Sky, 128 GB)',
 'REDMI 10 Prime (Phantom Black, 128 GB)',
 'realme C33 (Sandy Gold, 32 GB)',
 'realme C33 (Night Sea, 32 GB)',
 'realme C33 (Sandy Gold, 64 GB)',
 'realme C33 (Night Sea, 64 GB)',
 'realme C33 (Aqua Blue, 64 GB)',
 'REDMI 10A (Sea Blue, 64 GB)',
 'REDMI 10 Prime (Astral White, 128 GB)',
 'Micromax IN 2C (Brown, 32 GB)',
 'Micromax IN 2C (Silver, 32 GB)',
 'Infinix Smart 6 (Light Sea Green, 64 GB)',
 'Redmi 9A Sport (Coral Green, 32 GB)',
 'Redmi 9A Sport (Carbon Black, 32 GB)',
 'Infinix Smart 6 (Starry Purple, 64 GB)',
 'Infinix Smart 6 (Heart Of Ocean, 64 GB)']

In [19]:
price = []
N = driver.find_elements(By.XPATH,'//div[@class="_30jeq3 _1_WHN1"]')
for i in N:
    price.append(i.text)
price

['₹31,999',
 '₹14,499',
 '₹14,499',
 '₹15,999',
 '₹15,999',
 '₹17,999',
 '₹17,999',
 '₹15,999',
 '₹17,999',
 '₹12,999',
 '₹8,999',
 '₹8,999',
 '₹9,999',
 '₹9,999',
 '₹9,999',
 '₹8,945',
 '₹12,999',
 '₹5,499',
 '₹5,499',
 '₹6,699',
 '₹7,685',
 '₹6,797',
 '₹6,699',
 '₹6,699']

In [20]:
R = []
N = driver.find_elements(By.XPATH,'//span[@class="_2_R_DZ"]')
for i in N:
    R.append(i.text)
R

['46,720 Ratings & 6,979 Reviews',
 '63,470 Ratings & 4,693 Reviews',
 '63,470 Ratings & 4,693 Reviews',
 '36,381 Ratings & 2,870 Reviews',
 '36,381 Ratings & 2,870 Reviews',
 '4,387 Ratings & 370 Reviews',
 '4,387 Ratings & 370 Reviews',
 '36,381 Ratings & 2,870 Reviews',
 '4,387 Ratings & 370 Reviews',
 '7,308 Ratings & 538 Reviews',
 '13,450 Ratings & 532 Reviews',
 '13,450 Ratings & 532 Reviews',
 '40,321 Ratings & 1,646 Reviews',
 '40,321 Ratings & 1,646 Reviews',
 '40,321 Ratings & 1,646 Reviews',
 '5,179 Ratings & 335 Reviews',
 '7,308 Ratings & 538 Reviews',
 '732 Ratings & 94 Reviews',
 '732 Ratings & 94 Reviews',
 '23,491 Ratings & 1,586 Reviews',
 '5,476 Ratings & 421 Reviews',
 '22,542 Ratings & 1,734 Reviews',
 '23,491 Ratings & 1,586 Reviews',
 '23,491 Ratings & 1,586 Reviews']

In [21]:
Rating = []
N = driver.find_elements(By.XPATH,'//div[@class="_3LWZlK"]')
for i in N:
    Rating.append(i.text)
Rating

['4.5',
 '4.4',
 '4.4',
 '4.4',
 '4.4',
 '4.3',
 '4.3',
 '4.4',
 '4.3',
 '4.2',
 '4.5',
 '4.5',
 '4.5',
 '4.5',
 '4.5',
 '4.1',
 '4.2',
 '4.2',
 '4.2',
 '4.3',
 '4.2',
 '4.1',
 '4.3',
 '4.3']

In [23]:
B = pd.DataFrame()
B['NAME'] = name
B['PRICE'] = price
B['REVIEWS']=R
B['RATINGS'] = Rating
B

,NAME,PRICE,REVIEWS,RATINGS
0,"Google Pixel 4a (Just Black, 128 GB)","₹31,999","46,720 Ratings & 6,979 Reviews",4.5
1,"vivo T1 44W (Starry Sky, 128 GB)","₹14,499","63,470 Ratings & 4,693 Reviews",4.4
2,"vivo T1 44W (Midnight Galaxy, 128 GB)","₹14,499","63,470 Ratings & 4,693 Reviews",4.4
3,"vivo T1 44W (Starry Sky, 128 GB)","₹15,999","36,381 Ratings & 2,870 Reviews",4.4
4,"vivo T1 44W (Ice Dawn, 128 GB)","₹15,999","36,381 Ratings & 2,870 Reviews",4.4
5,"vivo T1 44W (Ice Dawn, 128 GB)","₹17,999","4,387 Ratings & 370 Reviews",4.3
6,"vivo T1 44W (Midnight Galaxy, 128 GB)","₹17,999","4,387 Ratings & 370 Reviews",4.3
7,"vivo T1 44W (Midnight Galaxy, 128 GB)","₹15,999","36,381 Ratings & 2,870 Reviews",4.4
8,"vivo T1 44W (Starry Sky, 128 GB)","₹17,999","4,387 Ratings & 370 Reviews",4.3
9,"REDMI 10 Prime (Phantom Black, 128 GB)","₹12,999","7,308 Ratings & 538 Reviews",4.2
10,"realme C33 (Sandy Gold, 32 GB)","₹8,999","13,450 Ratings & 532 Reviews",4.5
11,"realme C33 (Night Sea, 32 GB)","₹8,999","13,450 Ratings & 532 Reviews",4.5
12,"realme C33 (Sandy Gold, 64 GB)","₹9,999","40,321 Ratings & 1,646 Reviews",4.5
13,"realme C33 (Night Sea, 64 GB)","₹9,999","40,321 Ratings & 1,646 Reviews",4.5
14,"realme C33 (Aqua Blue, 64 GB)","₹9,999","40,321 Ratings & 1,646 Reviews",4.5
15,"REDMI 10A (Sea Blue, 64 GB)","₹8,945","5,179 Ratings & 335 Reviews",4.1
16,"REDMI 10 Prime (Astral White, 128 GB)","₹12,999","7,308 Ratings & 538 Reviews",4.2
17,"Micromax IN 2C (Brown, 32 GB)","₹5,499",732 Ratings & 94 Reviews,4.2
18,"Micromax IN 2C (Silver, 32 GB)","₹5,499",732 Ratings & 94 Reviews,4.2
19,"Infinix Smart 6 (Light Sea Green, 64 GB)","₹6,699","23,491 Ratings & 1,586 Reviews",4.3
20,"Redmi 9A Sport (Coral Green, 32 GB)","₹7,685","5,476 Ratings & 421 Reviews",4.2
21,"Redmi 9A Sport (Carbon Black, 32 GB)","₹6,797","22,542 Ratings & 1,734 Reviews",4.1
22,"Infinix Smart 6 (Starry Purple, 64 GB)","₹6,699","23,491 Ratings & 1,586 Reviews",4.3
23,"Infinix Smart 6 (Heart Of Ocean, 64 GB)","₹6,699","23,491 Ratings & 1,586 Reviews",4.3

In [2]:
driver = webdriver.Chrome(r'C:\Users\prasad kalekar\Selenium\chromedriver.exe')
driver.maximize_window()
driver = webdriver.Chrome('chromedriver.exe')
url = 'https://www.amazon.in/'

driver.get(url)

In [3]:
name = []
N = driver.find_elements(By.XPATH,'//span[@class="a-size-base-plus a-color-base a-text-normal"]')
for i in N:
    name.append(i.text)
name

['Kadence Slowhand Premium Jumbo Semi Acoustic Guitar with Heavy Padded Bag, guitar cable, Pro Capo (Black Spruce Wood)',
 "Gibz's G-38 Matte Acoustic Guitar With Truss Rod - Black",
 'Vault DA40 41 Inch Premium Solid Spruce-Top Dreadnought Acoustic Guitar',
 'Vault EA40 41 inch Premium Solid Spruce-Top Cutaway Acoustic Guitar',
 'Juârez Acoustic Guitar, 38 Inch Cutaway, 038C with Bag, Strings, Pick and Strap, Black',
 'Medellin 40" Acoustic Guitar +(Free Online Learning Course) - Durable Matt finish with, strings, strap, bag, 3 Picks and truss rod adjustment.',
 'Intern INT-38C Right hand Acoustic Guitar Kit, With Bag, Strings, Pick And Strap, Black, small',
 'Intern INT-38C Acoustic Guitar Kit (Blue)',
 'Kadence rosewood Guitar Frontier Series, Electric Acoustic Black Guitar With EQ, Die Cast Keys, Set Of Strings, Strap, Picks And Bag (Black EQ, Electric Acoustic)',
 'Juarez Acoustic Guitar, 38 Inch Curved Body Cutaway, 38CUR with Bag, Strings, Pick and Strap, Black',
 'Henrix 38C 38 Inch Cutaway Acoustic Guitar With Dual Action Truss Rod, Gigbag, Picks, String Set, String Winder, Strap, Polishing Cloth & Ebook - Black',
 'Intern INT-38C Acoustic Guitar Kit (Sunburst) with Carry bag, Picks, Strings set and Guitar Strap, Small',
 'Vault EA40 41 inch Premium Solid Spruce-Top Cutaway Acoustic Guitar',
 'Yamaha F280 Acoustic Rosewood Guitar (Natural, Beige)',
 'Fender CD 60 Dread V3 DS 6 String Acoustic Guitar - Walnut Fretboard-Black',
 'Yamaha FS100C Acoustic Guitar, Natural',
 '',
 '',
 'Juarez Acoustic Guitar Kit, 38 Inch Cutaway, 38C with Bag, Strings, Pick and Strap, 3TS Sunburst',
 'Juârez JRZ38C/WH 6 Strings Acoustic Guitar 38 Inch Cutaway, Right Handed, White with Bag, Strings, Picks and Strap',
 'Juarez Acoustic Guitar Kit, 38 Inch Cutaway, 38C with Bag, Strings, Pick and Strap, TBS Transparent Blue Sunburst',
 'Intern 38C Ebony Wood Cutaway Design Acoustic Guitar with Picks And Carry Bag (Black)',
 'Kadence Frontier guitar with Online Guitar learning course , Wine Red Acoustic Guitar with Die Cast Keys, Set of Strings, Strap, Picks and Bag (Wine Red, Acoustic)',
 'Yamaha F280 Acoustic Guitar, Tobacco Brown Sunburst',
 "LUCHILA 4 String Decor Guitar Children's Musical Instrument Educational Toy Small Guitar for Beginners Kids Child",
 'Vault PA36 Parlor Acoustic Guitar Kit',
 'Right Search ® Dancing Cactus and Guitar Set_CG1001',
 'Mustang 46 PCS Guitar Strings Changing Kit Guitar Tool Kit Including Guitar Strings Guitar Tuner Picks Capo Pins Guitar String Cutter and Winder for Beginner',
 'Yamaha FS100C Acoustic Guitar, Black',
 'Yamaha FX280 Tobacco Brown Sunburst Electro Acoustic Guitar',
 'YAMAHA FS80C NATURAL CONCERT CUTAWAY GUITAR',
 'Juarez Acoustic Guitar, 38 Inch Cutaway with Pick Guard, 38CPG with Bag, Strings, Pick and Strap, Black',
 'Hovner 215 Black F-Cut Rosewood Fretboard Acoustic Guitar With Bag,Strap,1 Set of Extra Strings and 2 Picks By K-Retail',
 'Yamaha FSX80C Semi acoustic cutaway guitar (natural)',
 'Hovner 215 Dark Green F-Cut Rosewood Fretboard Acoustic Guitar With Bag,Strap,1 Set of Extra Strings and 2 Picks By K-Retail',
 'YAMAHA F310, 6-Strings Rose Wood Acoustic Guitar, Natural',
 'Medellin M38 carbon fiber body 38 Incheses Acoustic Guitar (Blue Burst) Durable Matt finish With hAndrest, strings, strap, bag, 3 Picks, capo, stAnd',
 'Juarez Acoustic Guitar, 38 Inch Cutaway, 38CMB with Bag, Strings, Pick and Strap, Matte Black',
 'Yamaha F310-TBS Right Handed Acoustic Guitar (Tobacco Sunburst, 6-Strings)',
 'Medellin M38 carbon fiber body 38 Incheses Acoustic Guitar (Red) Durable Matt finish With hAndrest, strings, strap, bag, 3 Picks, capo, stAnd',
 'Yamaha FX280 Natural Electro Acoustic Guitar',
 "Hontral S4 String Decor Guitar Children's Musical Instrument Educational Toy Small Guitar for Beginners Kids Child - 23Inch",
 'Yamaha FSX80C Semi acoustic cutaway guitar (Black)',
 "G K Enterprise String Acoustic Guitar , Learning Toys for Girl & Boys,Musical Instrument Educational Guitar Toy for Beginners Kids 17'' - ( Pack of 1 )",
 'JUAREZ Arpeggio Guitar JRA41SP-RD-K, red',
 'JUAREZ Acoustic Guitar 3xE 1st String & 2 Pick Set JRGSE32',
 'Hovner Carlton Special Quality Rosewood Fretboard Blue Semi Acoustic Guitar With Bag,Strap,1 Set of Extra Strings and 2 Picks By K-Retail (Blue)',
 'Blueberry 38C, 38" Acoustic Guitar Kit with Bag, Strap, One Pack Strings And Picks (Black)',
 'A V Creation 4-String Kids Guitar | Musical Instrument for Boys Girls | Learning Toy Guitar for Kids | (17 Inches) Pack of 1',
 'Blueberry R-701, 6 String Right Handed Beginner Full Size Rosewood Fret board Electric Guitar with Bag, Strap, One Set of Strings and 2 Picks',
 'Medellin 38" Acoustic Guitar Carbon Fiber body+(Free Online Learning Course) - Durable Matt finish with handrest, strings, strap, bag, 3 Picks, capo, stand. (natural)',
 'Intern INT-38C Acoustic Guitar Kit (Red)',
 'Nema Guitar 4 in 1 Guitar Tuner + Capo + Pick Holder + 7 Picks',
 'Intern 38C Wooden Acoustic Steel-String Guitar Premium White Cutaway Design With Carry Bag, Strings, Guitar Strap And Plectrums (Int-38C-Wh)',
 'JUAREZ Arpeggio Guitar JRB40LN-3TS',
 "Firevally 4 String Guitar Children's Musical Instrument Educational Toy Guitar Ukulele Instruments Beginner Musical Sound Toys Best Gift for Children (Pack of 1)",
 'Fender SA-150C dreadnought Squier Guitar Cutway Natural',
 'Kadence Astro Man Electric Guitar, 24 FRETS, H- S - S PICK UPS Walnut Top with Alder wood Back and Sides (white) With Amplifier',
 'Belear I280 38 Inch Black Matt Spruce Cutaway, Acoustic Guitar, with Dual Action Truss Rod',
 'Medellin M38 carbon fiber body 38 Incheses Acoustic Guitar (Black) Durable Matt finish With hAndrest, strings, strap, bag, 3 Picks, capo, stAnd',
 'Right Search ® Mini Musical Guitar Toy _g1',
 'Right Search ®Musical Guitar and Drum Combo Set_GD2',
 'Pack of 2 Universal Guitar Stand by Hola! Music Fits Acoustic Classical Electric Bass Guitars Mandolins Banjos Ukuleles and Other Stringed Instruments',
 "Gibz's G-38 Glossy Acoustic Guitar With Truss Rod Natural"]

In [4]:
price = []
N = driver.find_elements(By.XPATH,'//span[@class="a-price-whole"]')
for i in N:
    price.append(i.text)
price

['6,499',
 '9,999',
 '5,199',
 '9,999',
 '4,498',
 '6,930',
 '7,290',
 '2,399',
 '3,499',
 '2,299',
 '6,999',
 '2,399',
 '5,219',
 '2,639',
 '2,799',
 '2,399',
 '7,290',
 '7,490',
 '12,770',
 '9,590',
 '',
 '',
 '2,639',
 '3,246',
 '2,639',
 '2,099',
 '5,199',
 '7,489',
 '899',
 '5,510',
 '1,399',
 '975',
 '9,100',
 '10,990',
 '7,727',
 '2,330',
 '4,480',
 '12,450',
 '4,480',
 '9,500',
 '2,599',
 '3,017',
 '9,737',
 '2,699',
 '11,299',
 '899',
 '12,490',
 '429',
 '5,442',
 '90',
 '4,750',
 '2,695',
 '459',
 '5,999',
 '2,699',
 '2,399',
 '777',
 '2,499',
 '5,686',
 '499',
 '6,849',
 '10,499',
 '2,999',
 '2,699',
 '299',
 '1,099',
 '999',
 '4,498']

In [5]:
rating = []
N = driver.find_elements(By.XPATH,'//span[@class="a-size-base s-underline-text"]')
for i in N:
    rating.append(i.text)
rating

['532',
 '1',
 '394',
 '17,983',
 '11,886',
 '222',
 '11,886',
 '1,370',
 '2,433',
 '1,658',
 '11,886',
 '394',
 '2,215',
 '1,077',
 '276',
 '',
 '',
 '5,352',
 '5,318',
 '5,643',
 '2,260',
 '1,794',
 '200',
 '1',
 '163',
 '339',
 '17',
 '187',
 '540',
 '660',
 '6',
 '1',
 '1,803',
 '169',
 '288',
 '62',
 '28',
 '21',
 '1',
 '18',
 '18',
 '7',
 '137',
 '162',
 '21',
 '3',
 '27',
 '11,886',
 '11,886',
 '5',
 '171',
 '10',
 '227',
 '28',
 '1']

In [6]:
d_type = []
N = driver.find_elements(By.XPATH,'//span[@class="a-color-base"]')
for i in N:
    d_type.append(i.text)
d_type

['',
 'Get it by',
 'FREE Delivery by Amazon',
 '',
 'Get it by',
 'FREE Delivery by Amazon',
 '',
 'Get it by',
 'FREE Delivery by Amazon',
 '',
 'Get it by',
 'FREE Delivery by Amazon',
 'Get it by',
 'FREE Delivery by Amazon',
 'Get it by',
 'FREE Delivery by Amazon',
 'Get it by',
 'FREE Delivery by Amazon',
 'Get it by',
 'FREE Delivery by Amazon',
 'Get it by',
 'FREE Delivery by Amazon',
 'Get it by',
 'FREE Delivery by Amazon',
 'Get it by',
 'FREE Delivery by Amazon',
 'Get it by',
 'FREE Delivery by Amazon',
 'Get it by',
 'FREE Delivery by Amazon',
 'Get it by',
 'FREE Delivery by Amazon',
 'Get it by',
 'FREE Delivery by Amazon',
 '₹7,348',
 'Get it by',
 'FREE Delivery by Amazon',
 'Get it by',
 'FREE Delivery by Amazon',
 'Get it by',
 'FREE Delivery by Amazon',
 'Get it by',
 'FREE Delivery by Amazon',
 'Get it by',
 'FREE Delivery by Amazon',
 'Get it by',
 'FREE Delivery by Amazon',
 '₹7,480',
 '',
 'Get it by',
 'FREE Delivery by Amazon',
 '',
 'Get it by',
 'FREE Delivery by Amazon',
 '',
 'Get it by',
 '',
 'Get it by',
 'Get it by',
 'FREE Delivery by Amazon',
 'Get it by',
 'FREE Delivery by Amazon',
 '₹10,589',
 'Get it by',
 'FREE Delivery by Amazon',
 'Get it by',
 'FREE Delivery by Amazon',
 'Get it by',
 'FREE Delivery by Amazon',
 'Get it by',
 'FREE Delivery by Amazon',
 '₹12,390',
 'Get it by',
 'FREE Delivery by Amazon',
 'Get it by',
 'FREE Delivery by Amazon',
 '₹9,450',
 'Get it by',
 'FREE Delivery by Amazon',
 'Get it by',
 'FREE Delivery by Amazon',
 'Get it by',
 'FREE Delivery by Amazon',
 '₹9,450',
 '',
 'with coupon',
 'Get it by',
 'FREE Delivery by Amazon',
 'Get it by',
 'FREE Delivery by Amazon',
 '₹10,700',
 'Get it by',
 'Get it by',
 'FREE Delivery by Amazon',
 '₹12,450',
 'Get it by',
 'Get it by',
 'FREE Delivery by Amazon',
 'Get it by',
 'FREE Delivery on first order.',
 'Get it by',
 'FREE Delivery by Amazon',
 'Get it by',
 'FREE Delivery by Amazon',
 'Get it by',
 'Get it by',
 'FREE Delivery by Amazon',
 '',
 'with coupon',
 'Get it by',
 'FREE Delivery by Amazon',
 'Get it by',
 'FREE Delivery by Amazon',
 'Get it by',
 'Get it by',
 'FREE Delivery by Amazon',
 'Get it by',
 'FREE Delivery by Amazon',
 'Get it by',
 'Get it by',
 'FREE Delivery by Amazon',
 'Get it by',
 'FREE Delivery by Amazon',
 'Get it by',
 '',
 'with coupon',
 'Get it by',
 'FREE Delivery by Amazon',
 '',
 'Get it by',
 '',
 'Get it by',
 '',
 'Get it by',
 '',
 'Get it by',
 'FREE Delivery by Amazon']

In [7]:
expect_d = []
N = driver.find_elements(By.XPATH,'//span[@class="a-color-base a-text-bold"]')
for i in N:
    expect_d.append(i.text)
expect_d

['Wednesday, November 23',
 'Thursday, November 24',
 'Friday, November 25',
 'Tuesday, November 22',
 'Wednesday, November 23',
 'Wednesday, November 23',
 'Tuesday, November 22',
 'Wednesday, November 23',
 'Thursday, November 24',
 'Tuesday, November 22',
 'tomorrow, November 21',
 'Friday, November 25',
 'Thursday, November 24',
 'Tuesday, November 22',
 'Wednesday, November 23',
 'Tuesday, November 22',
 'Thursday, November 24',
 'Thursday, November 24',
 'Thursday, November 24',
 'tomorrow, November 21',
 'Wednesday, November 23',
 'Friday, November 25',
 'Friday, November 25',
 'Friday, November 25',
 'Friday, November 25',
 'Wednesday, November 23',
 'Tuesday, November 22',
 'Wednesday, November 23',
 'Thursday, November 24',
 'Friday, November 25',
 'Tuesday, November 22',
 'Friday, November 25',
 'tomorrow, November 21',
 'Wednesday, November 23',
 'Tuesday, November 22',
 'Wednesday, November 23',
 'Tuesday, November 22',
 'Tuesday, November 22',
 'Friday, November 25',
 'Tuesday, November 22',
 'Friday, November 25',
 'Tuesday, November 22',
 'tomorrow, November 21',
 'Friday, November 25',
 'Friday, November 25',
 'Friday, November 25',
 'Friday, November 25',
 'Wednesday, November 23',
 'Thursday, November 24',
 'Wednesday, November 23',
 'Thursday, November 24',
 'Wednesday, November 23',
 'Friday, November 25',
 'Thursday, November 24',
 'Wednesday, November 23',
 'Sunday, November 27',
 'Tuesday, November 22',
 'Friday, November 25',
 'Friday, November 25',
 'Friday, November 25',
 'Thursday, November 24']

In [8]:
main_price = []
N = driver.find_elements(By.XPATH,'//span[@class="a-price a-text-price"]')
for i in N:
    main_price.append(i.text)
main_price

['₹8,670.00',
 '₹16,779.00',
 '₹7,680.00',
 '₹16,779',
 '₹8,999',
 '₹16,500',
 '₹17,800',
 '₹6,990',
 '₹6,999',
 '₹6,495',
 '₹8,800',
 '₹6,495',
 '₹6,800',
 '₹6,990',
 '₹5,500',
 '₹6,495',
 '₹17,800',
 '₹14,288',
 '₹9,990',
 '',
 '',
 '₹6,990',
 '₹6,990',
 '₹6,990',
 '₹4,995',
 '₹7,680',
 '₹7,490',
 '₹999',
 '₹12,000',
 '₹2,299',
 '₹1,599',
 '₹9,990',
 '₹11,490',
 '₹7,990',
 '₹6,990',
 '₹7,200',
 '₹12,490',
 '₹7,200',
 '₹4,999',
 '₹6,990',
 '₹9,990',
 '₹4,999',
 '₹11,490',
 '₹1,999',
 '₹1,399',
 '₹9,990',
 '₹390',
 '₹9,500',
 '₹6,995',
 '₹1,599',
 '₹15,990',
 '₹4,199',
 '₹6,495',
 '₹1,360',
 '₹6,995',
 '₹7,990',
 '₹1,999',
 '₹8,960',
 '₹13,999',
 '₹7,499',
 '₹4,999',
 '₹699',
 '₹1,799',
 '₹1,999',
 '₹8,999']

In [10]:
image = []
N = driver.find_elements(By.XPATH,'//img[@class="s-image"]')
for i in N:
    image.append(i.img)
image

AttributeError: 'WebElement' object has no attribute 'img'